app: "nano"
file_cpp: './a.out'
path_ai: "ai_request.json"
path_default: "projects/013_program.yaml"
course:
    name: Введение в теоретическую механику
    choice: 10
    sequence: 2
    matching: 5

data_prog: {
    'start': 'start program',
    'end': 'end program'
}
prompt: 'Представь, что ты автор курса "{name}". Напиши вопросы к теме "{themes}" по тезисам: {thesis}. Должно быть {choice} заданий тестовых на выбор одного или нескольких правильных ответов (choice), а также {sequence} на сортировку (sequence) и {matching} на сопоставление (matching). Ответ представь в формате json по образцу: '
template: '{
    "choice": [
    {
        "text": "Text question",
        "correct": ["correct"],
        "wrong": ["uncorrect_1", "uncorrect_2", "uncorrect_3"]
    }],
    "sequence": [
        {
            "text": "Text",
            "steps": ["one", "two", "three"]
        }
    ],
    "matching": [
    {
        "text": "Question",
        "therms": ["one", "two", "three"],
        "definitions": ["first", "second", "third"]
    }
    ]
}'
